config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :articles do
  	 resources :comments
  end

  get 'home/index'
  root 'home#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
end

app/models/clinic.rb
class Clinic

	require 'csv'

	attr_accessor :name, :hours, :address, :latitude, :longitude, :zip, :borough, :number

	def initialize(name)
		@name = name
		@zip = zip
		@borough = borough
		@number = number
	end

	def Clinic.all
		csv_text = File.read('clinics.csv')
		csv = CSV.parse(csv_text, headers: false)
		result = csv.map do |clinic|
		  c = Clinic.new(clinic[0])
		  if clinic[1].present?
		  	c.address = clinic[1]
		    c.latitude = clinic[7]
			c.longitude = clinic[8]
			c.name = clinic[0]
			c.zip = clinic[9]
			c.borough = clinic[2]
			c.number = clinic[3]
			c.hours = clinic[5]
		  else
		  	c.address = "Unknown"
		  end
		  c
		end
		result
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  	has_many :articles

  	def admin?
  		self.admin == true ? true : false
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    articles_path
  end

  protected

  def authenticate_admin!
  	unless current_user.admin?
  		flash[:notice] = "You do not have permission to do that."
  		redirect_to root_path
  	end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def show
  end

  def update
  @article.update(params[:article])
  redirect_to articles_path, notice: "Article succesfully updated."
  end

  def create
  @article = Article.create(article_params)
  redirect_to articles_path, notice: "New article created."
  end

  def destroy
  @article.destroy
  redirect_to articles_path, notice: "Article deleted."
  end


private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body).merge(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	  	@clinics = Clinic.all
		@hash = @clinics.map do |clinic|
			html = "<h4>#{clinic.name}</h4>Phone: #{clinic.number}</br>Address: #{clinic.address}"
			{lat: clinic.latitude.to_s, lng: clinic.longitude.to_s, 
			description: clinic.name, title: clinic.name, borough: clinic.borough,
			picture: {
	        	url: "http://icons.iconarchive.com/icons/medicalwp/medical/24/Hospital-blue-icon.png",
	        	width:  25,
	        	height: 25
      		}, 
			infowindow: html, sidebar: html}
     	end
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: [:edit, :update, :show, :destroy]


  def index
      @users = User.all
    end

  def new
    @user = User.new
  end

  def show
  end

  def update
    @user.update(params[:user])
    redirect_to users_path, notice: "User succesfully updated."
  end

  def create
    @user = User.create(params[:user])
    if @user.save
    redirect_to @user, notice: "New user created." 
  else
    render :new
    end

  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "User deleted successfully."
    else
      flash[:alert] = "There was a problem deleting the user."
    end
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :email, :newsletter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    	:user
  	end
 
 	def resource
    	@resource ||= User.new
  	end
 
  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
	
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

	<%= f.text_field :title, placeholder: :title %><br /><br />

	<%= f.text_area :body, placeholder: :body %><br />

	<%= f.submit %>

	<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<div class="container">
	<div class="page-header">
		<h1>NYC-SRC Articles Home Page</h1>
	</div>
		<div class="row">
			<div class="articles-list">
				<h3> New Articles</h3>
			<ul>
				<% @articles.each do |article| %>
				<li>
					<%=link_to article.title, article_path(article)%>
				</li>
			</ul>
			<%end%>
		</div>

		<section>
			<h3>Twitter Feed-Follow Us</h3>
		<div class="row">
			<div class="col-md-4">
			<a class="twitter-timeline" href="https://twitter.com/hiv_nyc" data-widget-id="573618627972308992">Tweets by @hiv_nyc</a> 
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
		</div>
		</section>
	</div>

</div>


	




		
		

app/views/articles/new.html.erb
<h1>Enter New Article</h1>
<%= render 'form' %>
<br />

<%= link_to 'show', articles_path %>

app/views/articles/show.html.erb
<!-- <h1></h1> -->



<!--<%# link_to 'new article', new_article_path %>!-->
<!--<%# link_to 'articlelist', root_path %> !-->

<div class="container-fluid">
	<div class="row">

			<div class="col-md-8 col-md-offset-2" id="show3">
				<h2 class="article-show"><%= @article.title %></h2>
				<p><%= @article.body %></p>
			</div>
	</div>
</div>

<h1><%=@article.title%></h1>
	<p> <%=@article.body%> </p>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/home/_articlelist.html.erb
<a id="Info"></a>

<div class="container"> 
		<div class="row">
			<div class="page-header">
				<h1>Recent Articles</h1>
			</div>
			
				<div class="col-md-4">
				<h2>Would A Pill To Protect Teens From HIV Make Them Feel Invincible?</h2>
				<h5>NPR: MARCH 11, 2015</h5>
				<p>Leon Richardson is 18 years old and tall, charismatic and thoughtful about his sexual health. He understands that as a young, gay black man, he is in the demographic with the highest rate of HIV infections in the country. But when Richardson learned that he could be part of an HIV prevention pill research study for young people, he was skeptical. "I was scared. I had to really think about it, 'What is this drug going to do to me?' " he says. <%= link_to 'read more', "http://www.npr.org/blogs/health/2015/03/11/392362374/would-a-pill-to-protect-teens-from-hiv-make-them-feel-invincible", target: "_blank" %> </p>

				</div>

				<div class="col-md-4">
				<h2>Drug abuse, dirty needles fueling HIV crisis in Indiana</h2>
				<h5>CBS News: April 7, 2015</h5>
				<p>Kevin Polly was diagnosed with HIV seven weeks ago. He's one of 89 new cases of HIV diagnosed in Austin, Indiana over the last few months. And yet, he has no plans to quit injecting a drug called Opana, an opiate painkiller being sold on the streets for $100 a pill. On the day Polly spoke with CBS News, he'd already done it three times -- before two o'clock in the afternoon. "The number one priority, you know, was to getting to feel better," Polly said.

 <%=link_to 'read more', "http://www.cbsnews.com/news/drug-abuse-dirty-needles-fueling-hiv-crisis-in-indiana/", target: "_blank" %></p>
				</div>

				<div class="col-md-4">
				<h2>Researchers find virus mimics an online infection</h2>
				<h5>DailyMail: April 2, 2015</h5>	
				<p>A new model for HIV progression shows that it spreads in a similar way to some computer 'worms'. HIV specialists and network security experts at University College London (UCL) made the disovery after creating a simulation of how the virus spreads. They worked together to build a model for this 'hybrid spreading' which accurately predicted patients' progression from HIV to AIDS in a major clinical trial - and say early treatment is key to staving off AIDS. 
				<%= link_to 'read more'," http://www.dailymail.co.uk/sciencetech/article-3023671/HIV-spreads-like-computer-virus-Researchers-spread-mimics-online-infection-warn-early-detection-key.html#ixzz3WjdG31U1", target: "_blank" %>
				</p>
				</div>
		</div><!--closes "row"!-->
	</div> <!-- closes container!-->

<div class="pictureart"></div>

app/views/home/_initial.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" id="my-navbar">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="" class="navbar-brand">NYC-SRC</a>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse">
		<% if user_signed_in? %>
			<a href="#Signin" class="btn btn-info navbar-btn navbar-right">Sign Out</a>
	
		<% else %>

			<a href="#Signin" class="btn btn-info navbar-btn navbar-right">Sign in</a>
		<% end %>

			<ul class="nav navbar-nav">
				<li><a href="#Map">Map</a></li>
				<li><a href="#Stats">Stats</a></li>
				<li><a href="#Info">Articles</a></li>
			</ul>
		</div>
	</div>
</nav>

<div class="images">
<div class="container">
	<div class="row">
		<div class="com-md-8">
			<h1 id="name_content">NYC-SRC</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 hidden-sm hidden-xs" id="name_content1">
			<h1 style="text-align: center">STATUS</h1> 
			<div class="pic1">
				<div class="text">
					<p><h4>Know your status</h4></p>
					<p> Search for free and low-cost health clinics in New York by borough</p>
				</div>
			</div>
		</div>
		<div class="col-md-4 hidden-sm hidden-xs" id="name_content1">
			<h1 style="text-align: center">RESOURCES</h1>
			<div class="pic2">
				<div class="text">
					<p><h4>Be Informed</h4></p>
					<p>Learn about latest statistics and information surrounding health in New York City</p>
				</div>
			</div>
		</div>
		<div class="col-md-4 hidden-sm hidden-xs" id="name_content1">
			<h1 style="text-align: center">CONNECTIONS</h1>
			<div class="pic3">
				<div class="text">
					<p><h4>Stay Connected</h4></p>
					<p>Join an online community where you can post articles and comment on current events</p>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

app/views/home/_map.html.erb
<a id="Map"></a>
<div class="container">
	<div class="row">
		<div class="page-header">
			<h2> Know Your Status - Search below to find a free testing center </h2>
		</div> 
	</div>
	
</div>
	
<!-- <div class="container">
	<h3>Search by Borough</h3>
	<div id="filter">
	<ul style= "list-style: none">
			<li><input type="radio" name="borough" id="bronxCheckbox" onclick="toggleGroup('Bronx')"/> Bronx </li>
			<li><input type="radio" name="borough" id="brooklynCheckbox" onclick="toggleGroup('Brooklyn')"/> Brooklyn</li>
			<li><input type="radio" name="borough" id="manhattanCheckbox" onclick="toggleGroup('Upper Manhattan')"/> Upper Manhattan
			</li>
			<li><input type="radio" name="borough" id="manhattanCheckbox" onclick="toggleGroup('Lower Manhattan')"/> Lower Manhattan</li>
			<li><input type="radio" name="borough" id="queensCheckbox" onclick="toggleGroup('Queens')"/> Queens </li>
			<li><input type="radio" name="borough" id="statenCheckbox" onclick="toggleGroup('Staten Island')"/> Staten Island
			</li>
		</ul>
	</div>
</div> -->

<div class="container">
	<h3>Search by Borough</h3>
	<div id="filter">
		<select id= "place" onchange="toggleGroup()">
			<option value="Bronx" > Bronx
			</option>
			<option value="Brooklyn">
				Brooklyn
			</option>
			<option>
				Queens
			</option>
			<option>
				Upper Manhattan
			</option>
			<option>
				Lower Manhattan
			</option>
			<option>
				Staten Island
			</option>
		</select>
	</div>
</div>
<br>


<div class="container">
	<div class="row">
		<div class="col-md-7">
			<div id="map-canvas" style="width: 80%; height: 400px;"></div>
		</div>
		<div class="col-md-5">
			<div id='sidebar_container'>
				<h3>Clinic Information</h3>
				<% @clinics.each do |f| %>
				<ul class=<%="#{f.borough}"%>>
					<li style="list-style: none">
						<strong><%=f.name%> </strong><br>
						<strong>Hours: </strong><%=f.hours%><br>
						<strong>Number: </strong><%=f.number%><br>
						<strong>Address: </strong><%=f.address%>
					</li>
				</ul>
				<% end%>

			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

var mapStyle = [
{
    "featureType": "all",
    "elementType": "all",
    "stylers": [
        { "hue": "#ff0000"},
        {"lightness": 4},
        {"saturation": -48}]
}];

clinics = <%= raw @hash.to_json %>;

var handler = Gmaps.build('Google');
handler.buildMap({
    internal: {id: 'map-canvas'},
    provider: {
      styles:    mapStyle
    }
  },

  function() {
 		markers = handler.addMarkers(clinics);
 		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
		_.each(clinics, function(json, index){
    json.marker = markers[index];
  });
	});

	function toggleGroup() {
		console.log(document.getElementById("place").value)
		var borough = document.getElementById("place").value
	  	var selected_clinics = [];
	    for (var i = 0; i < clinics.length; i++) {
		    if (clinics[i].borough == borough) {
		      selected_clinics.push(clinics[i])
		      var boroughClass = clinics[i].borough

		      var level = "." + boroughClass.split(' ');
		      var change =  level.split(',')
		      $(change[0]).css('display', 'block')
		    }
		    else{
		      var boroughClass = clinics[i].borough

		      var level = "." + boroughClass.split(' ');
		      var change =  level.split(',')
		      $(change[0]).css('display', 'none')

		    }
		}

	  	var handler = Gmaps.build('Google');
		handler.buildMap({
    	internal: {id: 'map-canvas'},
    	provider: {
      		styles: mapStyle
    	}
  	},
		
		function() {
	 		markers = handler.addMarkers(selected_clinics);
	 		handler.bounds.extendWith(markers);
			handler.fitMapToBounds();
		});
	};

</script>

<div class="empty"></div>

app/views/home/_signup.html.erb
<a id="Signin"></a>

<% if user_signed_in? %>
	<div class="container">
		<div class="row" id="sign">
			<%= current_user.email%> | <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
		</div>
	</div>
		
<% else %>

	<div class="container">
		<div class="row" id="sign">
			<h1>Keep in the loop</h1>
			<h3> Sign up to gain access to articles and an online communnity</h3>
			<h2>Sign In</h2>

		<%= simple_form_for(:user, :url => session_path(:user)) do |f| %>
		  <%= f.text_field :email, placeholder: :email%> <br/><br/>
		  <%= f.password_field :password, placeholder: :password %> <br/><br/>
		  <%= f.submit 'Sign in', :class => "btn" %> <br/><br/>
		  <%= f.check_box :remember_me %> 
		  <%= f.label :remember_me %><br/>
		  <%= link_to "Forgot your password?", new_password_path(:user) %> <br/>
		  <h3>Not Yet A User? Join the Conversation</h3>
		  <h4><%= link_to 'Join Us!', new_user_registration_path %></h4>
		</div>
	</div>
	
<%end%>
<%end%>

app/views/home/_stats.html.erb
<a id="Stats"></a>
 
<div class="container"> 
	<div class="row">
		<div class= "col-12-md">
			<div class="page-header">
				<h1>Stastics</h1>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-4"> 
		  	<div id="box1">
			  	<div class="circle" id="first-circle">
			  		<p id="circle_text1"> 20% </p>
			    </div>

			    <div id="stats1">
			    	<p>1 in 5 people who are HIV+ do not know thier status.</p>
			    </div>
			</div>
		</div>
		
		<div class="col-md-4"> 
			<div id="box2">
				<div class="circle" id="second-circle">
					<p id="circle_text2">33%</p>
				</div>

	    		<div id="stats2">
	    			<p>In the first half of 2011, one-third of new HIV/AIDS diagnoses among males in New York City were in young men aged 20-29.</p>
	    		</div>
		    </div>
		</div>	

		<div class="col-md-4"> 
			<div id="box3">
				<div class="circle" id="third-circle">
					<p id="circle_text3">#1</p>
				</div>
		    	
		    	<div id="stats3">
		    		<p>New York leads the nation in the number of new HIV cases.</p>
		    	</div>
		    </div>
		</div>	
	</div>
</div>
<br>
<br>

<div class="picture"></div>

app/views/home/index.html.erb
<!-- nav bar -->
<%=render 'initial' %>


<!--Map-->
<%=render 'map'%>
	
<!-- Stats -->
<%=render 'stats' %>

<!-- Article -->
<%=render 'articlelist'%>


<%=render 'signup'%>

app/views/layouts/_stats.html.erb
<div class="container">
	<div class="row">
		<body>
		  <div class="col-md-4" id="circle">
		    <div id="stats">Stats</div>
		  </div>
		</body>

		<body>
			<div class="col-md-4" id="circle">
		    	<div id="stats">Stats</div>
		  	</div>	
		</body>

		<body>
			<div class="col-md-4" id="circle">
		    	<div id="stats">Stats</div>
		  	</div>	
		</body>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HealthFinder</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<!-- 	<link rel="stylesheet" type="text/css" href="jquery.fullPage.css" />
	<script src="vendors/jquery.easings.min.js"></script>
<script type="text/javascript" src="jquery.fullPage.js"></script>
 -->

    <%= csrf_meta_tags %>
	
</head>
<body>
	<%= flash[:notice] if flash[:notice] %>
	<%= flash[:alert] if flash[:alert] %>
<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/index.html.erb
<h1>Listing all users</h1>



<ul>
	<% @users.each do |user| %>
		<li>
			<%= link_to user.username, user_path(user) %> | 
			<%= link_to 'delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"} %>|
			<%= link_to 'new user', new_user_path %>

		</li>
		<br>
	<% end %>
</ul>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>